client_max_body_size 30M;
client_body_buffer_size 64k;
client_body_temp_path /var/lib/nginx/tmp/client_body 1 2;
client_header_buffer_size 4k;
large_client_header_buffers 4 16k;

client_body_timeout 60s;
client_header_timeout 60s;
send_timeout 60s;

types_hash_max_size 2048;
types_hash_bucket_size 128;
